In [9]:
#import dependencies
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [10]:
# load draft data csv
draft_data = pd.read_csv('Draft_data.csv')
draft_data.head()

,player_id,name,college,assists,blocks,effective_field_goal_percentage,field_goal_percentage,free_throw_attempt_rate,free_throw_percentage,games_played,...,turnover_percentage,turnovers,win_shares_per_40_minutes,assists_per_40,blocks_per_40,points_per_40,steals_per_40,three_pointers_per_40,total_rebounds_per_40,turnovers_per_40
0,anthony-edwards-2,Anthony Edwards,missouri state,64,12,0.494,0.417,0.332,0.737,22,...,12.2,57,0.168,3.688761,0.691643,25.244957,1.729107,3.170029,6.628242,3.285303
1,james-wiseman-1,James Wiseman,memphis,1,9,0.769,0.769,1.038,0.704,3,...,7.2,3,0.444,0.579710,5.217391,34.202899,0.579710,0.000000,18.550725,1.739130
2,obadiah-toppin-1,Obi Toppin,dayton,109,57,0.675,0.648,0.306,0.718,55,...,14.8,115,0.245,2.802057,1.465296,23.367609,1.105398,0.822622,9.280206,2.956298
3,jaden-mcdaniels-1,Jaden McDaniels,washington,46,33,0.448,0.392,0.349,0.753,22,...,21.0,72,0.089,2.636103,1.891117,15.415473,1.031519,1.489971,7.392550,4.126074
4,nico-mannion-1,Nico Mannion,arizona,119,0,0.498,0.422,0.308,0.849,21,...,16.1,52,0.185,7.379845,0.000000,18.480620,1.426357,2.232558,3.472868,3.224806

In [11]:
# list(draft_data.columns.values)

In [12]:
X = draft_data.drop(['player_id','name','college','assists','blocks',
                     'effective_field_goal_percentage','free_throw_percentage','games_played',
                     'minutes_played','points','steals','three_pointers','total_rebounds',
                     'turnover_percentage','turnovers','assists_per_40','blocks_per_40',
                     'points_per_40','steals_per_40','three_pointers_per_40',
                     'total_rebounds_per_40','turnovers_per_40'], axis = 1)
X.head()

,field_goal_percentage,free_throw_attempt_rate,height,three_point_percentage,true_shooting_percentage,win_shares_per_40_minutes
0,0.417,0.332,77,0.329,0.533,0.168
1,0.769,1.038,85,0.000,0.760,0.444
2,0.648,0.306,81,0.400,0.685,0.245
3,0.392,0.349,81,0.313,0.497,0.089
4,0.422,0.308,75,0.350,0.548,0.185

In [15]:
# load the model from disk
filename = '../random_forest.pkl'
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

FileNotFoundError: [Errno 2] No such file or directory: '../random_forest.pkl'