In [1]:
#import dependencies
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [2]:
# load draft data csv
draft_data = pd.read_csv('Draft_data.csv')
draft_data.head()

,rank,player_id,name,college,year,assists,blocks,effective_field_goal_percentage,field_goal_percentage,free_throw_attempt_rate,...,turnover_percentage,turnovers,win_shares_per_40_minutes,assists_per_40,blocks_per_40,points_per_40,steals_per_40,three_pointers_per_40,total_rebounds_per_40,turnovers_per_40
0,1,anthony-edwards-2,Anthony Edwards,missouri state,Fr.,68,12,0.485,0.411,0.328,...,12.1,59,0.163,3.726027,0.657534,24.767123,1.808219,3.013699,6.958904,3.232877
1,2,james-wiseman-1,James Wiseman,memphis,Fr.,1,9,0.769,0.769,1.038,...,7.2,3,0.443,0.579710,5.217391,34.202899,0.579710,0.000000,18.550725,1.739130
2,4,obadiah-toppin-1,Obi Toppin,dayton,So.,111,60,0.674,0.646,0.306,...,14.6,116,0.244,2.792453,1.509434,23.295597,1.157233,0.830189,9.182390,2.918239
3,5,jaden-mcdaniels-1,Jaden McDaniels,washington,Fr.,49,35,0.453,0.396,0.347,...,21.2,77,0.087,2.673943,1.909959,15.552524,1.091405,1.527967,7.366985,4.201910
4,6,nico-mannion-1,Nico Mannion,arizona,Fr.,126,0,0.477,0.402,0.349,...,16.2,59,0.164,7.039106,0.000000,18.044693,1.396648,2.178771,3.407821,3.296089

In [3]:
# list(draft_data.columns.values)

In [9]:
X = draft_data[[
             "field_goal_percentage",
             "free_throw_attempt_rate",
             "height",
             "three_point_percentage",
             "true_shooting_percentage",
             "win_shares_per_40_minutes"
              ]]
X.head()

,field_goal_percentage,free_throw_attempt_rate,height,three_point_percentage,true_shooting_percentage,win_shares_per_40_minutes
0,0.411,0.328,77,0.318,0.526,0.163
1,0.769,1.038,85,0.000,0.760,0.443
2,0.646,0.306,81,0.398,0.684,0.244
3,0.396,0.347,81,0.318,0.499,0.087
4,0.402,0.349,75,0.339,0.531,0.164

In [10]:
X.dtypes

field_goal_percentage        float64
free_throw_attempt_rate      float64
height                         int64
three_point_percentage       float64
true_shooting_percentage     float64
win_shares_per_40_minutes    float64
dtype: object

In [11]:
# load the model from disk
filename = 'random_forest/random_forest_kfold.pkl'
loaded_model = pickle.load(open(filename, 'rb'))
# result = loaded_model.score(X_test, y_test)
print(loaded_model)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [22]:
# make a prediction
ynew = loaded_model.predict(X)

ynew

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0])

In [19]:
draft_data["rf_predict"]=y_new
draft_data[["name", "rf_predict"]].head(10)

                name  rf_predict
0    Anthony Edwards           0
1      James Wiseman           0
2         Obi Toppin           0
3    Jaden McDaniels           0
4       Nico Mannion           0
5       Daniel Oturu           1
6       Cole Anthony           0
7   Vernon Carey Jr.           1
8  Tyrese Haliburton           0
9     Onyeka Okongwu           1