In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from matplotlib import style
style.use("ggplot")

from sklearn.neighbors import KNeighborsClassifier
import os

In [10]:
df = pd.read_csv("NCAA_data.csv")
df.head()

,player_id,name,class,college,assists,blocks,effective_field_goal_percentage,field_goal_percentage,free_throw_attempt_rate,free_throw_percentage,...,turnovers,weight,win_shares_per_40_minutes,assists_per_40,blocks_per_40,points_per_40,steals_per_40,three_pointers_per_40,total_rebounds_per_40,turnovers_per_40
0,kenyon-martin-1,Kenyon Martin,Above Avg,cincinnati,142,292,0.587,0.586,0.494,0.581,...,139.0,234.0,0.346,2.781587,5.719882,25.053869,2.428991,0.039177,17.022527,2.722821
1,aj-guyton-1,A.J. Guyton,Below Avg,indiana,403,52,0.541,0.455,0.249,0.790,...,218.0,180.0,0.145,4.944785,0.638037,25.766871,1.582822,3.472393,5.263804,2.674847
2,jake-voskuhl-1,Jake Voskuhl,Below Avg,uconn,124,193,0.542,0.542,0.555,0.656,...,160.0,245.0,0.237,2.271062,3.534799,15.805861,1.575092,0.000000,16.117216,2.930403
3,khalid-el-amin-1,Khalid El-Amin,Bust,uconn,479,10,0.486,0.416,0.257,0.822,...,188.0,200.0,0.158,8.915775,0.186133,30.711959,3.462075,3.629595,5.937645,3.499302
4,mike-smith-1,Mike Smith,Bust,louisiana monroe,147,42,0.507,0.428,0.357,0.769,...,241.0,195.0,0.165,3.034056,0.866873,21.919505,1.857585,2.683179,9.267286,4.974200

In [9]:
df.shape

(853, 30)

In [50]:
df.dtypes

player_id                           object
name                                object
class                               object
college                             object
assists                              int64
blocks                               int64
effective_field_goal_percentage    float64
field_goal_percentage              float64
free_throw_attempt_rate            float64
free_throw_percentage              float64
games_played                         int64
height                              object
minutes_played                     float64
points                               int64
steals                               int64
three_point_percentage             float64
three_pointers                     float64
total_rebounds                       int64
true_shooting_percentage           float64
turnover_percentage                float64
turnovers                          float64
weight                             float64
win_shares_per_40_minutes          float64
assists_per_40                     float64
blocks_per_40                      float64
points_per_40                      float64
steals_per_40                      float64
three_pointers_per_40              float64
total_rebounds_per_40              float64
turnovers_per_40                   float64
dtype: object

In [56]:
X = ["steals_per_40","total_rebounds_per_40  "]

In [57]:
y = df["class"]
target_names = ["All_Star","Above_Average","Average","Below_Average","Bust"]

In [58]:
data = df.drop("class", axis =1)
feature_names = data.columns
data.head()

,player_id,name,college,assists,blocks,effective_field_goal_percentage,field_goal_percentage,free_throw_attempt_rate,free_throw_percentage,games_played,...,turnovers,weight,win_shares_per_40_minutes,assists_per_40,blocks_per_40,points_per_40,steals_per_40,three_pointers_per_40,total_rebounds_per_40,turnovers_per_40
0,kenyon-martin-1,Kenyon Martin,cincinnati,142,292,0.587,0.586,0.494,0.581,116,...,139.0,234.0,0.346,2.781587,5.719882,25.053869,2.428991,0.039177,17.022527,2.722821
1,aj-guyton-1,A.J. Guyton,indiana,403,52,0.541,0.455,0.249,0.790,128,...,218.0,180.0,0.145,4.944785,0.638037,25.766871,1.582822,3.472393,5.263804,2.674847
2,jake-voskuhl-1,Jake Voskuhl,uconn,124,193,0.542,0.542,0.555,0.656,138,...,160.0,245.0,0.237,2.271062,3.534799,15.805861,1.575092,0.000000,16.117216,2.930403
3,khalid-el-amin-1,Khalid El-Amin,uconn,479,10,0.486,0.416,0.257,0.822,108,...,188.0,200.0,0.158,8.915775,0.186133,30.711959,3.462075,3.629595,5.937645,3.499302
4,mike-smith-1,Mike Smith,louisiana monroe,147,42,0.507,0.428,0.357,0.769,55,...,241.0,195.0,0.165,3.034056,0.866873,21.919505,1.857585,2.683179,9.267286,4.974200

In [59]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data,target, random_state =42)

In [60]:
# Support vector machine linear classifier
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model.fit(X, y)

ValueError: could not convert string to float: 'steals_per_40'